# -*- coding: utf-8 -*-
"""IOT_Wearable_Context_Engine (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G9Km26PaSMyUZCJV3_wL1U5SiTd8Z-Bb
"""

!pip install -q langchain langgraph langchain-groq sentence-transformers chromadb

from google.colab import userdata
import os

# Before running: click the key icon (🔑) in Colab's left sidebar,
# add a secret named GROQ_API_KEY, paste your key, and toggle
# "Notebook access" on for this notebook.

GROQ_API_KEY = userdata.get('Groq_api')
os.environ["GROQ_API_KEY"] = GROQ_API_KEY

print("Groq key loaded:", GROQ_API_KEY[:8] + "..." if GROQ_API_KEY else "NOT FOUND")

from typing import TypedDict, List, Dict, Optional
from datetime import datetime

class TelemetryTick(TypedDict):
    timestamp: str
    heart_rate: int          # bpm
    accelerometer: float     # magnitude, roughly 0 (still) to 3+ (running)
    gps_speed: float         # km/h, 0 = stationary
    active_app: str          # e.g. "beads_counter", "navigation", "idle"
    battery: int              # percent

class AgentState(TypedDict):
    telemetry_window: List[TelemetryTick]   # rolling window of recent ticks
    profile_summary: Optional[str]           # Profiler Agent's output
    retrieved_context: Optional[List[str]]   # RAG chunks after rerank
    last_action: Optional[str]               # "silent" | "notify" | "emergency"
    last_reasoning: Optional[str]            # Action Agent's justification

def new_state() -> AgentState:
    """Factory for a fresh, empty AgentState."""
    return {
        "telemetry_window": [],
        "profile_summary": None,
        "retrieved_context": None,
        "last_action": None,
        "last_reasoning": None,
    }

import random
from datetime import datetime

def generate_tick(scenario: str = "normal") -> TelemetryTick:
    """
    Generates one mock telemetry reading.
    scenario controls which kind of situation gets simulated:
    'normal', 'sleeping', 'stressed_commuting', 'emergency_spike'
    """
    now = datetime.utcnow().isoformat()

    if scenario == "sleeping":
        hr = random.randint(48, 60)
        accel = round(random.uniform(0.0, 0.1), 2)
        speed = 0.0
        app = "idle"
    elif scenario == "stressed_commuting":
        hr = random.randint(95, 115)
        accel = round(random.uniform(0.3, 0.8), 2)
        speed = round(random.uniform(3, 15), 1)
        app = "navigation"
    elif scenario == "emergency_spike":
        hr = random.randint(140, 170)
        accel = round(random.uniform(0.0, 0.05), 2)   # HR spikes while sitting still
        speed = 0.0
        app = "idle"
    else:  # normal
        hr = random.randint(65, 85)
        accel = round(random.uniform(0.1, 0.3), 2)
        speed = round(random.uniform(0, 5), 1)
        app = random.choice(["beads_counter", "idle", "messaging"])

    return {
        "timestamp": now,
        "heart_rate": hr,
        "accelerometer": accel,
        "gps_speed": speed,
        "active_app": app,
        "battery": random.randint(15, 100),
    }

def generate_stream(n: int, scenario: str = "normal") -> List[TelemetryTick]:
    """Generates n ticks for a given scenario — useful for quick testing."""
    return [generate_tick(scenario) for _ in range(n)]

state = new_state()
state["telemetry_window"] = generate_stream(3, scenario="emergency_spike")

for tick in state["telemetry_window"]:
    print(tick)

import os

os.makedirs("corpus", exist_ok=True)

protocols_text = """
# Wearable Context Engine — Decision Protocols

## Heart Rate Anomalies
A heart rate above 140 bpm while the accelerometer shows near-zero movement
(under 0.1) and GPS speed is 0 suggests the user is physically still but the
body is under acute stress. This pattern is inconsistent with normal resting
states and warrants an emergency check-in rather than a passive notification.

## Sleep State Suppression
When heart rate is between 45 and 65 bpm, accelerometer readings are under
0.15, and the active app is idle, the user is likely asleep. Notifications
during this state should be suppressed unless the heart rate anomaly rule
above is also triggered.

## Commute Stress Handling
Elevated heart rate (90-120 bpm) combined with moderate accelerometer activity
and non-zero GPS speed typically indicates commuting stress, not a medical
event. The system should log this state but avoid interrupting the user,
since they are likely mid-navigation in an unfamiliar area.

## Battery-Constrained Behavior
If battery is below 10 percent, the system should minimize non-critical
notifications to preserve power for emergency detection, but must never
suppress an emergency escalation regardless of battery level.

## Escalation Threshold
An emergency protocol should only trigger when at least two independent
signals agree (for example, elevated heart rate AND lack of movement).
Acting on a single noisy signal risks false alarms and erodes user trust
in the system.
"""

with open("corpus/protocols.md", "w") as f:
    f.write(protocols_text)

print("protocols.md written:", os.path.getsize("corpus/protocols.md"), "bytes")

import json
import random

def generate_baseline_history(days: int = 7) -> dict:
    """Fully synthetic — no real person's data. Simulates a week of
    resting heart rate and past flagged episodes for one mock user."""
    history = []
    for d in range(days):
        history.append({
            "day": d + 1,
            "avg_resting_hr": random.randint(58, 68),
            "flagged_episodes": random.choice([0, 0, 0, 1])  # mostly quiet days
        })
    return {"user_id": "synthetic_user_001", "history": history}

baseline = generate_baseline_history()

with open("corpus/baseline_synthetic.json", "w") as f:
    json.dump(baseline, f, indent=2)

print(json.dumps(baseline, indent=2))

def chunk_markdown(text: str, min_chunk_len: int = 40) -> list:
    """
    Splits on markdown headers (##) so each chunk is one self-contained
    rule/topic — this is a natural chunk boundary for structured reference
    docs, better than fixed-size splitting which could cut a rule in half.
    """
    sections = text.split("## ")
    chunks = []
    for section in sections:
        section = section.strip()
        if len(section) < min_chunk_len:
            continue
        # re-add the header marker for readability, except for content before first header
        chunk = "## " + section if not section.startswith("#") else section
        chunks.append(chunk)
    return chunks

with open("corpus/protocols.md") as f:
    raw_text = f.read()

chunks = chunk_markdown(raw_text)

print(f"Total chunks: {len(chunks)}\n")
for i, c in enumerate(chunks):
    print(f"--- Chunk {i} ---")
    print(c[:], "\n")

from sentence_transformers import SentenceTransformer
import chromadb

# Load a small, free, local embedding model — no API calls, no cost
embedder = SentenceTransformer("BAAI/bge-small-en-v1.5")

# Persistent Chroma client — saves to disk so the DB survives across cells
chroma_client = chromadb.PersistentClient(path="./vectorstore")
collection = chroma_client.get_or_create_collection(name="protocols")

# Embed each chunk and add to the collection
embeddings = embedder.encode(chunks).tolist()
ids = [f"chunk_{i}" for i in range(len(chunks))]

collection.add(
    documents=chunks,
    embeddings=embeddings,
    ids=ids
)

print(f"Added {collection.count()} chunks to Chroma collection 'protocols'")

query = "user heart rate is very high but they are not moving"
query_embedding = embedder.encode([query]).tolist()

results = collection.query(
    query_embeddings=query_embedding,
    n_results=3
)

for doc, dist in zip(results["documents"][0], results["distances"][0]):
    print(f"distance: {dist:.4f}")
    print(doc[:150], "...\n")

from sentence_transformers import CrossEncoder

reranker = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")
print("Reranker loaded.")

def retrieve_and_rerank(query: str, top_k_retrieve: int = 5, top_k_final: int = 3) -> list:
    """
    Two-stage retrieval:
    1. Chroma does fast vector search to get top_k_retrieve candidates
    2. Cross-encoder reranks those candidates for precision, keeps top_k_final
    """
    query_embedding = embedder.encode([query]).tolist()
    results = collection.query(
        query_embeddings=query_embedding,
        n_results=top_k_retrieve
    )
    candidates = results["documents"][0]

    if not candidates:
        return []

    # Cross-encoder scores each (query, candidate) pair directly
    pairs = [[query, c] for c in candidates]
    scores = reranker.predict(pairs)

    # Sort candidates by reranker score, descending, keep top_k_final
    ranked = sorted(zip(candidates, scores), key=lambda x: x[1], reverse=True)
    return [doc for doc, score in ranked[:top_k_final]]

test_query = "battery is low but heart rate looks dangerous"
top_chunks = retrieve_and_rerank(test_query)

for i, chunk in enumerate(top_chunks):
    print(f"--- Reranked #{i+1} ---")
    print(chunk[:150], "...\n")

from langchain_groq import ChatGroq

profiler_llm = ChatGroq(
    model="llama-3.1-8b-instant",
    temperature=0,
    groq_api_key=GROQ_API_KEY
)

# Quick connectivity test
test_response = profiler_llm.invoke("Reply with exactly one word: OK")
print(test_response.content)

from langchain_core.messages import SystemMessage, HumanMessage

PROFILER_SYSTEM_PROMPT = """You are the Profiler Agent for a wearable device.
Given a rolling window of telemetry readings, summarize the user's current
state in ONE short sentence.

Use these reference ranges when describing heart rate:
- Below 60 bpm: low/resting
- 60-100 bpm: normal
- 100-140 bpm: elevated
- Above 140 bpm: dangerously high

Always explicitly state if heart rate is "dangerously high" when any reading
exceeds 140 bpm, especially if accelerometer is near 0 (meaning the user is
not moving). Do not soften or downplay high readings. Do not make medical
diagnoses, but be direct and factual about numbers that fall outside normal
ranges."""

def profiler_node(state: AgentState) -> AgentState:
    """
    Reads the telemetry window from state, asks the LLM for a one-line
    summary, and writes it back into state['profile_summary'].
    This is a LangGraph node: takes AgentState in, returns updated AgentState.
    """
    window = state["telemetry_window"]
    if not window:
        state["profile_summary"] = "No telemetry data available."
        return state

    # Format the window compactly to keep token usage low (Groq TPM limit)
    readings_text = "\n".join(
        f"HR:{t['heart_rate']} Accel:{t['accelerometer']} "
        f"Speed:{t['gps_speed']} App:{t['active_app']} Batt:{t['battery']}%"
        for t in window
    )

    messages = [
        SystemMessage(content=PROFILER_SYSTEM_PROMPT),
        HumanMessage(content=f"Recent readings:\n{readings_text}")
    ]

    response = profiler_llm.invoke(messages)
    state["profile_summary"] = response.content.strip()
    return state

test_state = new_state()
test_state["telemetry_window"] = generate_stream(4, scenario="emergency_spike")

test_state = profiler_node(test_state)
print("Profile summary:", test_state["profile_summary"])

action_llm = ChatGroq(
    model="openai/gpt-oss-120b",
    temperature=0,
    groq_api_key=GROQ_API_KEY
)

test_response = action_llm.invoke("Reply with exactly one word: OK")
print(test_response.content)

def do_nothing(reasoning: str):
    print(f"[SILENT] No action taken. Reasoning: {reasoning}")

def notify_user(reasoning: str):
    print(f"[NOTIFY] Sending notification to user. Reasoning: {reasoning}")

def trigger_emergency_protocol(reasoning: str):
    print(f"[EMERGENCY] Emergency protocol triggered! Reasoning: {reasoning}")

# Maps the LLM's chosen action label to the actual function to run
ACTION_MAP = {
    "silent": do_nothing,
    "notify": notify_user,
    "emergency": trigger_emergency_protocol,
}

import json

ACTION_SYSTEM_PROMPT = """You are the Action Agent for a wearable device.
You decide whether to stay silent, notify the user, or trigger an emergency
protocol, based on the user's current profile and relevant protocol rules.

Respond with ONLY a JSON object in this exact format, no other text:
{"action": "silent" | "notify" | "emergency", "reasoning": "one sentence explaining why"}

Follow the escalation rule: only choose "emergency" if at least two signals
in the profile agree on danger (e.g. high heart rate AND no movement)."""

def action_node(state: AgentState) -> AgentState:
    profile = state["profile_summary"] or "No profile available."
    window = state["telemetry_window"]

    # Compute hard numeric facts directly from data — no LLM interpretation involved
    max_hr = max(t["heart_rate"] for t in window) if window else 0
    min_accel = min(t["accelerometer"] for t in window) if window else 0
    min_battery = min(t["battery"] for t in window) if window else 100

    context_chunks = retrieve_and_rerank(profile, top_k_retrieve=5, top_k_final=3)
    state["retrieved_context"] = context_chunks
    context_text = "\n\n".join(context_chunks)

    user_message = f"""User profile (narrative): {profile}

Raw computed signals (trust these numbers over the narrative if they conflict):
- Max heart rate in window: {max_hr} bpm
- Min accelerometer in window: {min_accel}
- Min battery in window: {min_battery}%

Relevant protocol rules:
{context_text}

Decide the action."""

    messages = [
        SystemMessage(content=ACTION_SYSTEM_PROMPT),
        HumanMessage(content=user_message)
    ]

    response = action_llm.invoke(messages)
    raw = response.content.strip().replace("```json", "").replace("```", "").strip()

    try:
        parsed = json.loads(raw)
        action = parsed.get("action", "silent")
        reasoning = parsed.get("reasoning", "No reasoning provided.")
    except json.JSONDecodeError:
        action = "silent"
        reasoning = f"Could not parse model output: {raw}"

    state["last_action"] = action
    state["last_reasoning"] = reasoning

    action_fn = ACTION_MAP.get(action, do_nothing)
    action_fn(reasoning)

    return state

full_test_state = new_state()
full_test_state["telemetry_window"] = generate_stream(4, scenario="emergency_spike")

full_test_state = profiler_node(full_test_state)
print("Profile summary:", full_test_state["profile_summary"])
print()

full_test_state = action_node(full_test_state)
print()
print("Final action:", full_test_state["last_action"])
print("Reasoning:", full_test_state["last_reasoning"])

calm_state = new_state()
calm_state["telemetry_window"] = generate_stream(4, scenario="normal")

calm_state = profiler_node(calm_state)
calm_state = action_node(calm_state)

print("Final action:", calm_state["last_action"])

from langgraph.graph import StateGraph, END

def build_graph():
    """
    Assembles the two nodes into a linear LangGraph pipeline:
    profiler -> action -> end.
    We keep it linear for now (no branching) since the branching
    logic already lives inside action_node's JSON decision — LangGraph
    here mainly gives us a clean, extensible structure to add more
    nodes to later (e.g. a retriever node, a memory node).
    """
    graph = StateGraph(AgentState)

    graph.add_node("profiler", profiler_node)
    graph.add_node("action", action_node)

    graph.set_entry_point("profiler")
    graph.add_edge("profiler", "action")
    graph.add_edge("action", END)

    return graph.compile()

app_graph = build_graph()
print("Graph compiled successfully.")

input_state = new_state()
input_state["telemetry_window"] = generate_stream(4, scenario="stressed_commuting")

result_state = app_graph.invoke(input_state)

print("\n--- Final Result ---")
print("Profile:", result_state["profile_summary"])
print("Action:", result_state["last_action"])
print("Reasoning:", result_state["last_reasoning"])

# Bypass the graph entirely — just check what generate_stream produces
emergency_ticks = generate_stream(4, scenario="emergency_spike")
normal_ticks = generate_stream(4, scenario="normal")

print("=== emergency_spike ticks ===")
for t in emergency_ticks:
    print(t)

print("\n=== normal ticks ===")
for t in normal_ticks:
    print(t)

import time
def run_simulation(scenario: str, num_ticks: int = 4, delay_seconds: float = 1.0):
    state = new_state()

    for round_num in range(3):
        state["telemetry_window"] = generate_stream(num_ticks, scenario=scenario)

        # DEBUG: print the actual ticks right before they go into the graph
        print(f"--- Round {round_num + 1} raw ticks (scenario={scenario}) ---")
        for t in state["telemetry_window"]:
            print(t)

        state = app_graph.invoke(state)

        print(f"\n=== Round {round_num + 1} ===")
        print("Profile:", state["profile_summary"])
        print("Action:", state["last_action"])
        print("-" * 50)

        time.sleep(delay_seconds)

    return state

final_state = run_simulation(scenario="emergency_spike", num_ticks=4, delay_seconds=2.0)

final_state = run_simulation(scenario="normal", num_ticks=4, delay_seconds=2.0)

test_scenarios = [
    {"id": 1, "scenario": "emergency_spike", "expected_action": "emergency"},
    {"id": 2, "scenario": "emergency_spike", "expected_action": "emergency"},
    {"id": 3, "scenario": "normal", "expected_action": "silent"},
    {"id": 4, "scenario": "normal", "expected_action": "silent"},
    {"id": 5, "scenario": "sleeping", "expected_action": "silent"},
    {"id": 6, "scenario": "sleeping", "expected_action": "silent"},
    {"id": 7, "scenario": "stressed_commuting", "expected_action": "silent"},
    {"id": 8, "scenario": "stressed_commuting", "expected_action": "silent"},
]

import json
with open("eval_test_scenarios.json", "w") as f:
    json.dump(test_scenarios, f, indent=2)

print(f"Saved {len(test_scenarios)} test scenarios.")

import time

def run_evaluation(scenarios: list, num_ticks: int = 4, delay_seconds: float = 2.0) -> list:
    """
    Runs the compiled graph once per test scenario, records the actual
    action taken, and compares it against the expected_action label.
    """
    results = []

    for case in scenarios:
        state = new_state()
        state["telemetry_window"] = generate_stream(num_ticks, scenario=case["scenario"])
        state = app_graph.invoke(state)

        actual = state["last_action"]
        correct = (actual == case["expected_action"])

        results.append({
            "id": case["id"],
            "scenario": case["scenario"],
            "expected": case["expected_action"],
            "actual": actual,
            "correct": correct,
            "reasoning": state["last_reasoning"]
        })

        print(f"Case {case['id']} ({case['scenario']}): "
              f"expected={case['expected_action']}, actual={actual}, "
              f"{'✅' if correct else '❌'}")

        time.sleep(delay_seconds)  # stay under Groq's rate limit

    return results

eval_results = run_evaluation(test_scenarios)

def score_results(results: list):
    total = len(results)
    correct = sum(1 for r in results if r["correct"])
    accuracy = correct / total if total > 0 else 0

    # Emergency-specific recall — the metric that matters most for safety
    emergency_cases = [r for r in results if r["expected"] == "emergency"]
    emergency_caught = sum(1 for r in emergency_cases if r["actual"] == "emergency")
    emergency_recall = emergency_caught / len(emergency_cases) if emergency_cases else None

    # False positives — non-emergency cases that got escalated anyway
    false_emergencies = [r for r in results if r["expected"] != "emergency" and r["actual"] == "emergency"]

    print(f"Overall accuracy: {correct}/{total} ({accuracy:.0%})")
    if emergency_recall is not None:
        print(f"Emergency recall: {emergency_caught}/{len(emergency_cases)} ({emergency_recall:.0%})")
    print(f"False emergency triggers: {len(false_emergencies)}")

    if false_emergencies:
        print("\n⚠️ False emergency cases (review these):")
        for r in false_emergencies:
            print(f"  Case {r['id']} ({r['scenario']}): {r['reasoning']}")

score_results(eval_results)

with open("eval_results.json", "w") as f:
    json.dump(eval_results, f, indent=2)

print("Eval results saved to eval_results.json")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile core.py
# import os
# import json
# import random
# from datetime import datetime, timezone
# from typing import TypedDict, List, Optional
# 
# from sentence_transformers import SentenceTransformer, CrossEncoder
# import chromadb
# from langchain_groq import ChatGroq
# from langchain_core.messages import SystemMessage, HumanMessage
# from langgraph.graph import StateGraph, END
# 
# # ---------- State ----------
# class TelemetryTick(TypedDict):
#     timestamp: str
#     heart_rate: int
#     accelerometer: float
#     gps_speed: float
#     active_app: str
#     battery: int
# 
# class AgentState(TypedDict):
#     telemetry_window: List[TelemetryTick]
#     profile_summary: Optional[str]
#     retrieved_context: Optional[List[str]]
#     last_action: Optional[str]
#     last_reasoning: Optional[str]
# 
# def new_state() -> AgentState:
#     return {
#         "telemetry_window": [],
#         "profile_summary": None,
#         "retrieved_context": None,
#         "last_action": None,
#         "last_reasoning": None,
#     }
# 
# # ---------- Simulator ----------
# def generate_tick(scenario: str = "normal") -> TelemetryTick:
#     now = datetime.now(timezone.utc).isoformat()
#     if scenario == "sleeping":
#         hr, accel, speed, app = random.randint(48, 60), round(random.uniform(0.0, 0.1), 2), 0.0, "idle"
#     elif scenario == "stressed_commuting":
#         hr, accel, speed, app = random.randint(95, 115), round(random.uniform(0.3, 0.8), 2), round(random.uniform(3, 15), 1), "navigation"
#     elif scenario == "emergency_spike":
#         hr, accel, speed, app = random.randint(140, 170), round(random.uniform(0.0, 0.05), 2), 0.0, "idle"
#     else:
#         hr, accel, speed, app = random.randint(65, 85), round(random.uniform(0.1, 0.3), 2), round(random.uniform(0, 5), 1), random.choice(["beads_counter", "idle", "messaging"])
#     return {"timestamp": now, "heart_rate": hr, "accelerometer": accel, "gps_speed": speed, "active_app": app, "battery": random.randint(15, 100)}
# 
# def generate_stream(n: int, scenario: str = "normal") -> List[TelemetryTick]:
#     return [generate_tick(scenario) for _ in range(n)]
# 
# # ---------- RAG components (loaded once, cached by Streamlit) ----------
# def load_rag_components():
#     embedder = SentenceTransformer("BAAI/bge-small-en-v1.5")
#     reranker = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")
#     chroma_client = chromadb.PersistentClient(path="./vectorstore")
#     collection = chroma_client.get_or_create_collection(name="protocols")
#     return embedder, reranker, collection
# 
# def retrieve_and_rerank(query, embedder, reranker, collection, top_k_retrieve=5, top_k_final=3):
#     query_embedding = embedder.encode([query]).tolist()
#     results = collection.query(query_embeddings=query_embedding, n_results=top_k_retrieve)
#     candidates = results["documents"][0]
#     if not candidates:
#         return []
#     pairs = [[query, c] for c in candidates]
#     scores = reranker.predict(pairs)
#     ranked = sorted(zip(candidates, scores), key=lambda x: x[1], reverse=True)
#     return [doc for doc, score in ranked[:top_k_final]]
# 
# # ---------- Prompts ----------
# PROFILER_SYSTEM_PROMPT = """You are the Profiler Agent for a wearable device.
# Given a rolling window of telemetry readings, summarize the user's current
# state in ONE short sentence.
# 
# Use these reference ranges when describing heart rate:
# - Below 60 bpm: low/resting
# - 60-100 bpm: normal
# - 100-140 bpm: elevated
# - Above 140 bpm: dangerously high
# 
# Always explicitly state if heart rate is "dangerously high" when any reading
# exceeds 140 bpm, especially if accelerometer is near 0. Do not soften or
# downplay high readings. Do not make medical diagnoses, but be direct and
# factual about numbers outside normal ranges."""
# 
# ACTION_SYSTEM_PROMPT = """You are the Action Agent for a wearable device.
# You decide whether to stay silent, notify the user, or trigger an emergency
# protocol, based on the user's current profile and relevant protocol rules.
# 
# Respond with ONLY a JSON object in this exact format, no other text:
# {"action": "silent" | "notify" | "emergency", "reasoning": "one sentence explaining why"}
# 
# Follow the escalation rule: only choose "emergency" if at least two signals
# in the profile agree on danger (e.g. high heart rate AND no movement)."""
# 
# # ---------- Graph builder ----------
# def build_graph(embedder, reranker, collection, groq_api_key):
#     profiler_llm = ChatGroq(model="llama-3.1-8b-instant", temperature=0, groq_api_key=groq_api_key)
#     action_llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0, groq_api_key=groq_api_key)
# 
#     def profiler_node(state: AgentState) -> AgentState:
#         window = state["telemetry_window"]
#         if not window:
#             state["profile_summary"] = "No telemetry data available."
#             return state
#         readings_text = "\n".join(
#             f"HR:{t['heart_rate']} Accel:{t['accelerometer']} Speed:{t['gps_speed']} App:{t['active_app']} Batt:{t['battery']}%"
#             for t in window
#         )
#         messages = [SystemMessage(content=PROFILER_SYSTEM_PROMPT), HumanMessage(content=f"Recent readings:\n{readings_text}")]
#         response = profiler_llm.invoke(messages)
#         state["profile_summary"] = response.content.strip()
#         return state
# 
#     def action_node(state: AgentState) -> AgentState:
#         profile = state["profile_summary"] or "No profile available."
#         window = state["telemetry_window"]
#         max_hr = max(t["heart_rate"] for t in window) if window else 0
#         min_accel = min(t["accelerometer"] for t in window) if window else 0
#         min_battery = min(t["battery"] for t in window) if window else 100
# 
#         context_chunks = retrieve_and_rerank(profile, embedder, reranker, collection)
#         state["retrieved_context"] = context_chunks
#         context_text = "\n\n".join(context_chunks)
# 
#         user_message = f"""User profile (narrative): {profile}
# 
# Raw computed signals (trust these numbers over the narrative if they conflict):
# - Max heart rate in window: {max_hr} bpm
# - Min accelerometer in window: {min_accel}
# - Min battery in window: {min_battery}%
# 
# Relevant protocol rules:
# {context_text}
# 
# Decide the action."""
# 
#         messages = [SystemMessage(content=ACTION_SYSTEM_PROMPT), HumanMessage(content=user_message)]
#         response = action_llm.invoke(messages)
#         raw = response.content.strip().replace("```json", "").replace("```", "").strip()
# 
#         try:
#             parsed = json.loads(raw)
#             action = parsed.get("action", "silent")
#             reasoning = parsed.get("reasoning", "No reasoning provided.")
#         except json.JSONDecodeError:
#             action, reasoning = "silent", f"Could not parse model output: {raw}"
# 
#         state["last_action"] = action
#         state["last_reasoning"] = reasoning
#         return state
# 
#     graph = StateGraph(AgentState)
#     graph.add_node("profiler", profiler_node)
#     graph.add_node("action", action_node)
#     graph.set_entry_point("profiler")
#     graph.add_edge("profiler", "action")
#     graph.add_edge("action", END)
#     return graph.compile()

import os
from google.colab import userdata

os.makedirs(".streamlit", exist_ok=True)

groq_key = userdata.get('Groq_api')

with open(".streamlit/secrets.toml", "w") as f:
    f.write(f'GROQ_API_KEY = "{groq_key}"\n')

print("secrets.toml written.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile streamlit_app.py
# import streamlit as st
# import os
# from core import new_state, generate_stream, load_rag_components, build_graph
# 
# st.set_page_config(page_title="Wearable Context Engine", layout="wide")
# st.title("IoT Wearable Context Engine — Live Dashboard")
# 
# # API key: works both for local/tunnel testing (env var) and Streamlit Cloud (st.secrets)
# groq_api_key = st.secrets.get("GROQ_API_KEY", os.environ.get("GROQ_API_KEY"))
# 
# # Cache expensive resources so they load once, not on every interaction
# @st.cache_resource
# def get_pipeline():
#     embedder, reranker, collection = load_rag_components()
#     graph = build_graph(embedder, reranker, collection, groq_api_key)
#     return graph
# 
# app_graph = get_pipeline()
# 
# if "log" not in st.session_state:
#     st.session_state.log = []
# 
# with st.sidebar:
#     st.header("Controls")
#     scenario = st.selectbox("Simulated scenario", ["normal", "sleeping", "stressed_commuting", "emergency_spike"])
#     num_ticks = st.slider("Ticks per round", 2, 8, 4)
#     run_button = st.button("Run one round")
# 
# if run_button:
#     state = new_state()
#     state["telemetry_window"] = generate_stream(num_ticks, scenario=scenario)
#     with st.spinner("Running agent pipeline..."):
#         state = app_graph.invoke(state)
#     st.session_state.log.append({
#         "scenario": scenario,
#         "profile": state["profile_summary"],
#         "action": state["last_action"],
#         "reasoning": state["last_reasoning"],
#         "context": state["retrieved_context"],
#     })
# 
# col1, col2 = st.columns(2)
# 
# with col1:
#     st.subheader("Current State")
#     if st.session_state.log:
#         latest = st.session_state.log[-1]
#         st.write("**Profile summary:**", latest["profile"])
#         action_color = {"silent": "🟢", "notify": "🟡", "emergency": "🔴"}
#         st.write(f"**Action:** {action_color.get(latest['action'], '')} {latest['action']}")
#         st.write("**Reasoning:**", latest["reasoning"])
#         st.write("**Retrieved context:**")
#         for chunk in latest["context"] or []:
#             st.caption(chunk[:200])
#     else:
#         st.info("Click 'Run one round' to start.")
# 
# with col2:
#     st.subheader("Decision Log")
#     if st.session_state.log:
#         st.table([
#             {"Scenario": r["scenario"], "Action": r["action"]}
#             for r in st.session_state.log
#         ])

!pkill ngrok
!pkill streamlit
!pkill -9 ngrok
!pkill -9 streamlit
!pkill -9 python

!pip install -q streamlit pyngrok

import subprocess
import time
from google.colab import userdata
from pyngrok import ngrok

# 1. Auth ngrok
NGROK_AUTH_TOKEN = userdata.get('ngrok_key')
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# 2. CLEANUP (The fix for the connection error)
print("🔄 Cleaning up old tunnels...")
try:
    # Explicitly tell the ngrok cloud to disconnect active tunnels
    tunnels = ngrok.get_tunnels()
    for tunnel in tunnels:
        ngrok.disconnect(tunnel.public_url)

    # Kill the local process
    ngrok.kill()

    # CRITICAL: Give the ngrok cloud backend 5-10 seconds to register the release
    print("⏳ Waiting for ngrok cloud to release your domain...")
    time.sleep(8)
except Exception as e:
    print(f"Cleanup note: {e}")

# 3. Run Streamlit in the background
print("📦 Starting Streamlit...")
streamlit_process = subprocess.Popen(
    ["streamlit", "run", "streamlit_app.py", "--server.port", "8501", "--server.headless", "true"]
)
time.sleep(5)

# 4. Open a public tunnel
try:
    print("🔗 Connecting tunnel...")
    public_url = ngrok.connect(8501)
    print("\n🚀 Streamlit app is live at:", public_url)
except Exception as e:
    print(f"\n❌ Connection failed: {e}")
    print("💡 Quick Fix: Go to https://dashboard.ngrok.com/endpoints and manually clear the active endpoint.")

import shutil

# Zip everything needed for the repo
shutil.make_archive("wearable_context_engine", "zip", ".",
    logger=None)

# List what's being included (sanity check)
import os
for f in ["core.py", "streamlit_app.py", "corpus", "vectorstore"]:
    print(f, "exists:", os.path.exists(f))

import shutil, os

os.makedirs("repo_files", exist_ok=True)
for item in ["core.py", "streamlit_app.py", "corpus", "vectorstore"]:
    if os.path.isdir(item):
        shutil.copytree(item, f"repo_files/{item}", dirs_exist_ok=True)
    else:
        shutil.copy(item, "repo_files/")

shutil.make_archive("repo_files", "zip", "repo_files")
print("Created repo_files.zip — download this from the Colab file browser (left sidebar).")

